# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.CharField(max_length=50)),
                ('positionName', models.CharField(max_length=50)),
                ('playerfirstName', models.CharField(max_length=100)),
                ('playerlastName', models.CharField(max_length=100)),
                ('teamAbbreviation', models.CharField(max_length=50)),
                ('teamCity', models.CharField(max_length=100)),
                ('teamName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRawStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerStatKey', models.CharField(max_length=100)),
                ('statisticType', models.CharField(max_length=100)),
                ('statAmt', models.IntegerField(default=0)),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerdata.Player')),
            ],
        ),
    ]
