# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrawstats',
            name='dateStat',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of stat'),
            preserve_default=False,
        ),
    ]
