# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0002_playerrawstats_datestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrawstats',
            name='playerID',
            field=models.CharField(max_length=50),
        ),
    ]
