# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerdata', '0005_auto_20170113_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='PergameTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergameTotalKey', models.CharField(max_length=100)),
                ('dateStat', models.DateField(verbose_name='date of stat')),
                ('playerID', models.CharField(max_length=50)),
                ('statAmt', models.FloatField(default=0)),
            ],
        ),
    ]
